### ISSUE TITLE
EPIC - Bet Creation

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#1]
As a superuser I want to add a bet via the admin page and view it on the site.  

**User Stories**
- [x] #2 
- [x] #3
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #7 
- [x] #8 
- [ ]

**Acceptance Criteria**
- [x] Django Project and App created
- [x] Project Deployed to Heroku
- [x] Bet models are created with relationship mapping
- [x] Bet can be made with multiple lines
- [x] Necessary Bet information is displayed on the webpage
- [x] Necessary Line information is displayed on the webpage
- [x] User information is displayed as the bet creator
