### ISSUE TITLE
User Story - Base template

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#10]
As a **user**, I want to **have consistent styling across all pages** so that **the site is accessible and familiar**

Epic: #9 

## Acceptance Criteria
- [x] Open bets html page inherits from base.html template
- [x] Custom CSS styles are applied to enhance bootstrap framework
- [ ]

## Tasks
- [x] Create base.html template
- [x] Implement bootstrap framework to customise the site
- [x] Create a Nav bar and Footer in base.html
- [ ]
