### ISSUE TITLE
User Story - Display settled bets

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#11]
As a **user**, I want to **view all settled bets** so that **I can review all previous betting activity**

Epic: #9 

## Acceptance Criteria
- [x] Settled Bets page inherits from Base.html
- [x] Settled Bets are displayed on a single page with no pagination
- [x] All information about each bet is displayed to the user
- [x] Bets are ordered, most recent at the top
- [x] Only settled bets are displayed
- [x] Winning bets are clearly distinguishable from losing bets

## Tasks
- [ ] Create new view for settled bets
- [ ] 
- [ ]
