### ISSUE TITLE
User Story - Bet creation form

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#12]
As a **user**, I want to **add a bet to the site** so that **share with others and track my success**

Epic: #9

## Acceptance Criteria
- [ ] User can add a bet to the site
- [ ] Entry into all data fields is validated
- [ ] User can add multiple lines to the bet
- [ ] Default bet status is 'pending'
- [ ] Error is displayed to the user if mandatory fields are left empty
- [ ] User is notified when the bet is added successfully
- [ ] Form must be styled consistently with the rest of the site
- [ ] User is prompted for confirmation before adding the bet

## Tasks
- [ ] 
- [ ] 
- [ ]
