### ISSUE TITLE
User Story - Edit open bet

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#13]
As a **user**, I want to **edit my open bets** so that **update the result, status and make any necessary corrections**

Epic: #9 

## Acceptance Criteria
- [x] User can update the match result of any line
- [x] User can edit the bet stake to another valid amount
- [x] User can edit the odds to another valid amount
- [x] User can edit all lines
- [x] All fields are validated before the updates are applied
- [x] User is notified of the successful changes
- [x] Only the user who placed the bet can edit the bet
- [ ] 

## Tasks
- [x] Pre-populate bet data into the form when editing
- [ ] 
- [ ]
