### ISSUE TITLE
User Story - Delete an open bet

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#14]
As a **user**, I want to **delete an open bet** so that **the bet details are removed from the database**

Epic: #9 

## Acceptance Criteria
- [x] User is sent a notification to confirm the bet has been deleted
- [x] Bet is removed from the database
- [x] All lines are removed from the database
- [x] User is prompted that all lines will be deleted 
- [x] User is prompted for confirmation before bet is deleted
- [x] Only the user who placed the bet can delete the bet

## Tasks
- [x] Create confirmation modal to warn user before deleting the bet
- [ ] 
- [ ]
