### ISSUE TITLE
User Story - Filter open bets

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#15]
As a **user**, I want to **filter the open bets** so that **only my bets are displayed**

Epic: #9

## Acceptance Criteria
- [ ] Only users bets are displayed
- [ ] A single click can switch between the full list and filtered list
- [ ] It is clearly displayed to the user which view they are looking at
- [ ] Bets are ordered with the most recently updated at the top

## Tasks
- [ ] 
- [ ] 
- [ ]
