### ISSUE TITLE
User Story - Filter settled bets

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#16]
As a **user**, I want to **filter the settled bets** so that **only my bets are displayed**

Epic: #9 

## Acceptance Criteria
- [ ] Only users bets are displayed
- [ ] A single click can switch between the full list and filtered list
- [ ] It is clearly displayed to the user which view they are looking at
- [ ] Bets are ordered with the most recently closed / settled at the top
- [ ]

## Tasks
- [ ] 
- [ ] 
- [ ]
