### ISSUE TITLE
User Story - Account Registration

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#19]
As a **visitor**, I want to **register to the site** so that **i can use the site and track my bets**

Epic: #

## Acceptance Criteria
- [ ] User provides unique username 
- [x] Email address entry is optional
- [ ]

## Tasks
- [x] Create registration form
- [x] Install Django-allauth package
- [ ]
