### ISSUE TITLE
User Story - Create Django Project

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#2]
As a developer, I want to create a Django Project in the IDE, so that I have the framework for the Bet Tracker project

Epic #1 

## Acceptance Criteria
- [x] Django installed in the IDE
- [x] Django folder structure present in the IDE
- [x] Requirements text file created and populated

## Tasks
- [ ] 
- [ ] 
- [ ]
