### ISSUE TITLE
User Story - User Login

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#20]
As a **user**, I want to **login to the site** so that **I can make changes to my bets, and make new bets**

Epic: #18 

## Acceptance Criteria
- [x] Users not logged in can only view the bets and money list on the site
- [x] Login page styled consistently with the site
- [x] Sign up page styled consistently with the site

## Tasks
- [ ] 
- [ ] 
- [ ]
