### ISSUE TITLE
User Story - Account logout

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#21]
As a **user**, I want to **logout of the site** so that **my account is not logged in when i am not using the site**

Epic: #18 

## Acceptance Criteria
- [x] User can no longer edit, add, delete bets when they have logged out
- [x] User can still view the site and bet information
- [x] User is given notification that they have successfully logged out

## Tasks
- [ ] 
- [ ] 
- [ ]

**Comment by bmays9** [comment]
Tasks for this User story were completed as part of #20 . Acceptance Testing specifically for this User Story was all that was required. Testing is successful.
