### ISSUE TITLE
User Story - Style home page

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#23]
As a **user**, I want to **see information presented intelligently and cleanly on the site** so that **the site is easy to read**

Epic: #9

## Acceptance Criteria
- [x] Bets are displayed clearly with status of each line shown
- [x] Collapsible bet display to show only the summary of later bets
- [x] Most recent bets are expanded
- [x] Allow space for CRUD buttons

## Tasks
- [ ] 
- [ ] 
- [ ]
