### ISSUE TITLE
User Story - Bank app model

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#24]
As a **user**, I want to **see my account balance on the homepage** so that **i know how successful my bets are**

Epic: #17 

## Acceptance Criteria
- [x] User's balance is displayed on the Home page
- [x] Negative balances are shown in red
- [x] Positive balances are shown in green (including zero)
- [x] Amount with maximum number of characters is displayed clearly

## Tasks
- [x] Create Bank Model in Django App
- [x] Pass user's balance to home page
- [ ]

**Comment by bmays9** [comment]
Updated pass criteria so positve balances are shown in green, not black

**Comment by bmays9** [comment]
Passed
