### ISSUE TITLE
User Story - Deployment with static files

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#25]
As a **user**, I want to **see the deployed project with intended styling** so that **I view the site as intended**

Epic: #9 

## Acceptance Criteria
- [x] Hosted project uses the same styling as the development site
- [ ] 
- [ ]

## Tasks
- [x] Install whitenoise to the IDE
- [x] Add the Python version to runtime.txt
- [x] Remove DISABLE_COLLECTSTATIC from Heroku config vars
- [ ]
