### ISSUE TITLE
User Story - Automated Testing for Adding, Editing, and Deleting a Bet

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#27]
As a **tester**, I want to **automate tests to the bet form function** so that **i can ensure the functions work as expected**

Epic: #9 

## Acceptance Criteria
- [ ] Adding a bet function is tested with automated tests
- [ ] Editing a bet function is tested with automated tests
- [ ] Deleting a bet function is tested with automated tests

## Tasks
- [ ] 
- [ ] 
- [ ]
