### ISSUE TITLE
User Story - Update Bank account when settling a bet

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#28]
As a **user**, I want to **track my betting account balance ** so that **I can see how profitable my bets are**

Epic: #9 #17 

## Acceptance Criteria
- [x] Bank balance is decreased by the stake amount when a losing bet is settled
- [x] Bank balance is increased by the returned amount when a winning bet is settled

## Tasks
- [x] Ensure all users have a unique bank balance when first bet is settled

- [ ]
