### ISSUE TITLE
User Story - Create Bet App

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#3]
As a **developer**, I want to **have a Bet app created in the Django project ** to **facilitate the bet tracking element of the project**

Epic: #1 

## Acceptance Criteria
- [x] Bet app folder structure is present in the IDE
- [x] "bet/" url pattern displays "Hello, Bet app" message in test environment
- [x] bet is listed as an Installed App

## Tasks
- [ ] 
- [ ] 
- [ ]
