### ISSUE TITLE
User Story - Instructive Home Page

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#30]
As a **user**, I want to **view a home page that explains how to use the site** so that ** a casual viewers can unfamiliar with betting can use the site**

Epic: #9 

## Acceptance Criteria
- [x] new home page now loads for '/' address 
- [x] all nav bar links work
- [x] 'bets/' is the new address for the bet list pages

## Tasks
- [x] update links for current '/' home page 
- [x] all references to homepage must be moved to 'bets page'
- [x] create new home.html
