### ISSUE TITLE
User Story - Custom Error Pages

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#32]
As a **site owner**, I want to **have custom error pages** so that **users know that they are still on my website and are guided back to the home page**

Epic: #

## Acceptance Criteria
- [ ] Custom 404 Error Page displays appropriately, inheriting from base.html
- [ ] Custom 403 Error Page displays appropriately, inheriting from base.html 
- [ ] Custom 500 Error Page displays appropriately, inheriting from base.html

## Tasks
- [x] Create 404.html
- [x] Create 403.html 
- [x] Create 500.html

**Comment by bmays9** [comment]
Tasks were completed but the acceptance criteria was not met.
As this is only an optional 'could have' feature, there was no resolution.
