### ISSUE TITLE
User Story - Create Bank App

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#4]
As a **developer**, I want to **have a Bank app in the Django project** to **facilitate the money tracking and user ranking elements of the project**

Epic: #1

## Acceptance Criteria
- [x] Bank app folder structure is present in the IDE
- [x] "bank/" url pattern displays "Hello, Bank app" message
- [x] Bank is listed as an Installed App

## Tasks
- [ ] 
- [ ] 
- [ ]
