### ISSUE TITLE
User Story - Deploy project to Heroku

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#5]
As a **project**, I want to be **deployed to Heroku**, so that **I am available to all potential users**.

Epic: #1 

## Acceptance Criteria
- [x] Project is deployed to Heroku without errors
- [x] bet/ url pattern displays "Hello, Bet app" message 
- [x] bank/ url pattern displays "Hello, Bank app" message 

## Tasks
- [ ] 
- [ ] 
- [ ]
