### ISSUE TITLE
User Story - Database and Models

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#6]
As a **developer**, I want to **set up and configure my database and Bet app models**, so that **data can be added via the admin page**

Epic: #1 

## Acceptance Criteria
- [x] Line data can be entered via Admin page with all fields populated
- [x] Bet data can be entered via Admin page with all fields populated
- [x] Multiple lines can be associated with a single Bet
- [x] A line can be assigned to one Bet only
- [x] Superuser can add, delete, update and view Line records
- [x] Superuser can add, delete, update and view Bet records
- [x] Project is deployed to Heroku without errors

## Tasks
- [x] Create models for Bet app
- [x] Create PostgreSQL instance
- [x] Connect Database to code
- [x] Create superuser
- [x] Enter Bet Data via Admin page
- [x] Enter Line Data via Admin page
