### ISSUE TITLE
User Story - Configure Admin Functionality

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#7]
As a **superuser** I want to **have an admin page that is customised to the project** , so that **the data and admin functions are presented in an intelligent way**

Epic: #1 

## Acceptance Criteria
- [x] Bets can be filtered by user on the admin page
- [x] Bets can be filtered by status on the admin page
- [x] Bets are ordered with the most recent at the top on the admin page
- [ ]

## Tasks
- [x] Create second superuser 
- [x] Add 2 bets for each user, one with a single line, one with multiple lines
- [x] Install Summernote and add to Installed Apps list
