### ISSUE TITLE
User Story - Display open bets

### ISSUE THREAD

**Issue by bmays9** [bmays9/bet-tracker#8]
As a **user**, I want to **view all open bets** so that **I can see what other users bets are upcoming**

Epic: #1 

## Acceptance Criteria
- [x] All open bets are displayed to the user on the home page
- [x] All lines of each bet is displayed to the user
- [x] Bets are ordered, most recent at the top
- [x] Bets are displayed on a single page

## Tasks
- [ ] 
- [ ] 
- [ ]
